# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-04-09 00:36
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('jedi_hr', '0004_auto_20170409_0035'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='candidateanswer',
            name='quiz',
        ),
        migrations.AddField(
            model_name='candidateanswer',
            name='answer',
            field=models.BooleanField(default=None),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='candidateanswer',
            name='question',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='jedi_hr.Question'),
            preserve_default=False,
        ),
    ]
