# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-04-09 13:18
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('jedi_hr', '0005_auto_20170409_0036'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='jedi',
            name='age',
        ),
    ]
